### ISSUE TITLE
jms分布式事务问题

### ISSUE THREAD

**Issue by ipqihujf** [jasonGeng88/springboot-jms#1]
生产者和消费者整合到一起一直打印这个是什么问题？？
2017-08-31 11:06:53.972  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: creating XA-capable session...
2017-08-31 11:06:53.997  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: calling hashCode on JMS driver...
2017-08-31 11:06:53.998  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: calling start on JMS driver...
2017-08-31 11:06:54.000  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: calling createQueue on JMS driver session...
2017-08-31 11:06:54.000  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: calling createConsumer on JMS driver session ActiveMQSession {id=ID:PC201507091454-4690-1504148809585-1:1:2,started=true} java.lang.Object@56bf9487
2017-08-31 11:06:54.036  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsMessageConsumerProxy  : atomikos MessageConsumer proxy for ActiveMQMessageConsumer { value=ID:PC201507091454-4690-1504148809585-1:1:2:1, started=true }: receive ( 1000 )...
2017-08-31 11:06:54.037  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsMessageConsumerProxy  : atomikos MessageConsumer proxy for ActiveMQMessageConsumer { value=ID:PC201507091454-4690-1504148809585-1:1:2:1, started=true }: receive ( 1000 , null )...
2017-08-31 11:06:54.038  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.CompositeTransactionImp   : registerSynchronization ( com.atomikos.jms.ConsumerProducerSupport$JmsRequeueSynchronization@64c5dd63 ) for transaction 192.168.56.1.tm0000100033
2017-08-31 11:06:54.040  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.CompositeTransactionImp   : addParticipant ( XAResourceTransaction: 3139322E3136382E35362E312E746D30303030313030303333:3139322E3136382E35362E312E746D31 ) for transaction 192.168.56.1.tm0000100033
2017-08-31 11:06:54.040  INFO 9528 --- [enerContainer-1] c.a.datasource.xa.XAResourceTransaction  : XAResource.start ( 3139322E3136382E35362E312E746D30303030313030303333:3139322E3136382E35362E312E746D31 , XAResource.TMNOFLAGS ) on resource jmsConnectionFactory represented by XAResource instance TransactionContext{transactionId=null,connection=ActiveMQConnection {id=ID:PC201507091454-4690-1504148809585-1:1,clientId=ID:PC201507091454-4690-1504148809585-0:2,started=true}}
2017-08-31 11:06:54.081  INFO 9528 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2017-08-31 11:06:54.088  INFO 9528 --- [           main] cn.shenxd.ActivemqProducerApplication    : Started ActivemqProducerApplication in 8.423 seconds (JVM running for 8.879)
2017-08-31 11:06:55.041  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: calling getTransacted on JMS driver session...
2017-08-31 11:06:55.045  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsMessageConsumerProxy  : atomikos MessageConsumer proxy for ActiveMQMessageConsumer { value=ID:PC201507091454-4690-1504148809585-1:1:2:1, started=true }: close...
2017-08-31 11:06:55.045  INFO 9528 --- [enerContainer-1] c.a.datasource.xa.XAResourceTransaction  : XAResource.end ( 3139322E3136382E35362E312E746D30303030313030303333:3139322E3136382E35362E312E746D31 , XAResource.TMSUCCESS ) on resource jmsConnectionFactory represented by XAResource instance TransactionContext{transactionId=XID:[1096044365,globalId=3139322e3136382e35362e312e746d30303030313030303333,branchId=3139322e3136382e35362e312e746d31],connection=ActiveMQConnection {id=ID:PC201507091454-4690-1504148809585-1:1,clientId=ID:PC201507091454-4690-1504148809585-0:2,started=true}}
2017-08-31 11:06:55.046  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: closing session atomikos xa session proxy for resource jmsConnectionFactory - is terminated ? false
2017-08-31 11:06:55.047  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: close()...
2017-08-31 11:06:55.048  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.CompositeTransactionImp   : commit() done (by application) of transaction 192.168.56.1.tm0000100033
2017-08-31 11:06:55.157  INFO 9528 --- [enerContainer-1] c.a.datasource.xa.XAResourceTransaction  : XAResource.commit ( 3139322E3136382E35362E312E746D30303030313030303333:3139322E3136382E35362E312E746D31 , true ) on resource jmsConnectionFactory represented by XAResource instance TransactionContext{transactionId=null,connection=ActiveMQConnection {id=ID:PC201507091454-4690-1504148809585-1:1,clientId=ID:PC201507091454-4690-1504148809585-0:2,started=true}}
2017-08-31 11:06:55.158  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.BaseTransactionManager    : createCompositeTransaction ( 10000 ): created new ROOT transaction with id 192.168.56.1.tm0000200033
2017-08-31 11:06:55.158  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosConnectionFactoryBean    : AtomikosConnectionFactoryBean 'jmsConnectionFactory': createConnection()...
2017-08-31 11:06:55.159  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosConnectionFactoryBean    : AtomikosConnectionFactoryBean 'jmsConnectionFactory': init...
2017-08-31 11:06:55.159  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: creating XA-capable session...
2017-08-31 11:06:55.160  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: calling hashCode on JMS driver...
2017-08-31 11:06:55.160  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsConnectionProxy       : atomikos connection proxy for resource jmsConnectionFactory: calling start on JMS driver...
2017-08-31 11:06:55.160  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: calling createQueue on JMS driver session...
2017-08-31 11:06:55.160  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsXaSessionProxy        : atomikos xa session proxy for resource jmsConnectionFactory: calling createConsumer on JMS driver session ActiveMQSession {id=ID:PC201507091454-4690-1504148809585-1:1:4,started=true} java.lang.Object@41a595d4
2017-08-31 11:06:55.161  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsMessageConsumerProxy  : atomikos MessageConsumer proxy for ActiveMQMessageConsumer { value=ID:PC201507091454-4690-1504148809585-1:1:4:1, started=true }: receive ( 1000 )...
2017-08-31 11:06:55.161  INFO 9528 --- [enerContainer-1] c.a.jms.AtomikosJmsMessageConsumerProxy  : atomikos MessageConsumer proxy for ActiveMQMessageConsumer { value=ID:PC201507091454-4690-1504148809585-1:1:4:1, started=true }: receive ( 1000 , null )...
2017-08-31 11:06:55.161  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.CompositeTransactionImp   : registerSynchronization ( com.atomikos.jms.ConsumerProducerSupport$JmsRequeueSynchronization@667ab602 ) for transaction 192.168.56.1.tm0000200033
2017-08-31 11:06:55.162  INFO 9528 --- [enerContainer-1] c.a.icatch.imp.CompositeTransactionImp   : addParticipant ( XAResourceTransaction: 3139322E3136382E35362E312E746D30303030323030303333:3139322E3136382E35362E312E746D32 ) for transaction 192.168.56.1.tm0000200033

**Comment by jasonGeng88** [comment]
我这边整合了一下，没出现你这问题。
从你的日志上也没看出有错误级别的异常，能具体说说你是怎么整合的吗？

我的整合过程：
  1. 在 producer 的 Application 中添加一个 jmsQueueListenerContainerFactory()
  2. 添加一个监听器，PtpListener1
  3. 启动 producer

**Comment by ipqihujf** [comment]
按照你的producer，分布式配置代码
复制到consumer之后，在启动consumer就会报上面的错误

**Comment by TysonMJ** [comment]
直接启动那个XAApplication,然后访问controller 会报这个错,
AtomikosTransactionRequiredJMSException : The JMS session you are using requires a JTA transaction context for the calling thread and none was found.
Please correct your code to do one of the following: 
1. start a JTA transaction if you want your JMS operations to be subject to JTA commit/rollback, or
2. increase the maxPoolSize of the AtomikosConnectionFactoryBean to avoid transaction timeout while waiting for a connection, or
3. create a non-transacted session and do session acknowledgment yourself, or
4. set localTransactionMode to true so connection-level commit/rollback are enabled.

然后再访问另一个url报另一个错javax.naming.NamingException: Another resource already exists with name xa - pick a different name
	at com.atomikos.util.IntraVmObjectFactory.createReference(IntraVmObjectFactory.java:94) ~[atomikos-util-3.9.3.jar:na]
	at com.atomikos.jms.AtomikosConnectionFactoryBean.getReference(AtomikosConnectionFactoryBean.java:646) [transactions-jms-3.9.3.jar:na]
	at com.atomikos.jms.AtomikosConnectionFactoryBean.init(AtomikosConnectionFactoryBean.java:359) [transactions-jms-3.9.3.jar:na]
	at com.atomikos.jms.AtomikosConnectionFactoryBean.createConnection(AtomikosConnectionFactoryBean.java:615) [transactions-jms-3.9.3.jar:na]
	at org.springframework.jms.support.JmsAccessor.createConnection(JmsAccessor.java:180) [activemq-all-5.15.9.jar:5.15.9]
	at org.springframework.jms.core.JmsTemplate.execute(JmsTemplate.java:474) [activemq-all-5.15.9.jar:5.15.9]
	at org.springframework.jms.core.JmsTemplate.send(JmsTemplate.java:570) [activemq-all-5.15.9.jar:5.15.9]
	at org.springframework.jms.core.JmsTemplate.convertAndSend(JmsTemplate.java:658) [activemq-all-5.15.9.jar:5.15.9]
	at com.how2java.mq.activemq.workobj.PtpProducer.convertAndSend(PtpProducer.java:34) [classes/:na]
	at com.how2java.mq.activemq.webtest.TestController.convertAndSendptp(TestController.java:46) [classes/:na]
	at com.how2java.mq.activemq.webtest.TestController$$FastClassBySpringCGLIB$$1c1a842d.invoke(<generated>) [classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) [spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669) [spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.how2java.mq.activemq.webtest.TestController$$EnhancerBySpringCGLIB$$8889a0ae.convertAndSendptp(<generated>) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) [spring-webmvc-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-embed-websocket-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-all-1.3.2.jar:1.3.2]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) [spring-web-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.23.jar:8.5.23]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
